# Generated by Django 5.2.6 on 2025-10-16 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_laboratorios/')),
            ],
        ),
        migrations.CreateModel(
            name='LoincCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loinc_num', models.CharField(max_length=20, unique=True)),
                ('shortname', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.TextField(blank=True, null=True)),
                ('property', models.CharField(blank=True, max_length=50, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('scale_typ', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Biometría Hemática', max_length=150, unique=True)),
                ('tipo_formato', models.CharField(choices=[('RESULTADOS', 'Resultados (Solo propiedades y valores)'), ('IMAGENES_RESULTADOS', 'Imágenes y Resultados'), ('RECETA_JUSTIFICADA', 'Receta Justificada (Solo texto)')], default='RESULTADOS', max_length=50)),
                ('texto_justificado_default', models.TextField(blank=True, help_text="Usado solo si el formato es 'Receta Justificada'", null=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Análisis',
                'verbose_name_plural': '1. Plantillas de Análisis (Crear aquí)',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='labApp.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('fecha_muestra', models.DateField(blank=True, null=True)),
                ('hora_toma', models.TimeField(blank=True, null=True)),
                ('hora_impresion', models.TimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labApp.paciente')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analisis', to='labApp.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propiedad', models.CharField(help_text='Ej: Hemoglobina, Glucosa', max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('loinc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labApp.loinccode')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='labApp.plantilla')),
            ],
            options={
                'verbose_name': 'Propiedad de Plantilla',
                'verbose_name_plural': '2. Propiedades de Plantillas (Añadir Intervalos aquí)',
            },
        ),
        migrations.CreateModel(
            name='IntervaloReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_edad', models.CharField(choices=[('NINO', 'Niño'), ('ADULTO', 'Adulto'), ('ADULTO_MAYOR', 'Adulto Mayor')], max_length=20)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10)),
                ('valor_min', models.FloatField()),
                ('valor_max', models.FloatField()),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='labApp.propiedadplantilla')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propiedad', models.CharField(max_length=100)),
                ('valor', models.CharField(blank=True, max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='labApp.analisis')),
                ('loinc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labApp.loinccode')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('num_telefono', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('laboratorios', models.ManyToManyField(blank=True, related_name='usuarios', to='labApp.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('PENDIENTE', 'Pendiente')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='labApp.usuario')),
            ],
        ),
    ]
